### PR TITLE
classification bridge files

### PR DESCRIPTION
**Pull request by ghost**
I've included here two new raw data files: both sector classification bridges for common sector classification codes, along with relevant data dictionaries. 

note: pr is draft, as I am not sure best method for adding these two new dictionaries into data_dictionary.R (currently only the loanbook.csv dictionary is rolled up, and this is done individually/ manually. maybe best to automate this process?)

@maurolepore for context: Bank will use varying sector classification codes in their portfolios (and occasionally they won't use codes at all). We incorporate translation bridges between these varying codes, and 2dii's relevant sectors, e.g.
`c('power', 'oil and gas', 'coal', 'automotive', 'aviation', 'concrete', 'steel', 'shipping')`

### CODE REVIEW

**Comment by maurolepore** [comment]
@jhoff-2dii, 

I liked you idea of automating the process for extending `data_dictionary` when a new dataset is added. The approach I took is enabled by the new version of `create_data_dictionary()` (6facb60), which now allows you to define `<new_data>` directly on data-raw/data_dictionary.R (7429e27) and eliminates the need of `data-raw/data_dictionary_<new_data>.csv`.

Combined with `datapasta::tribble_paste()`,   `create_data_dictionary()` is handy to document datasets with relatively short definitions ([example](https://github.com/jhoff-2dii/r2dii.dataraw/blob/62e5c2321ba4f1d40254959693b5df214f87d386/data-raw/data_dictionary.R#L30)):

image

Unfortunately, it's awkward to define datasets with long definitions ([example](https://github.com/jhoff-2dii/r2dii.dataraw/blob/62e5c2321ba4f1d40254959693b5df214f87d386/data-raw/data_dictionary.R#L8)). So I'm open to discuss other alternatives.  What would you suggest?

**Comment by jdhoffa** [comment]
hey @maurolepore, FYI i will be doing all my work from this account from now on. deleting my old account will delete all open pull requests (this is the only one still existing) so once we resolve this I will delete my other account. 

From a high level, what I had in mind was more along the lines of the following:
- continue as before, defining both dataset and data_dictionary whenever a new dataset is to be incorporated
- not yet define the true data_dictionary file, but include a script that runs on build, generating the data_dictionary (run through all *.csv in some data_dictionary folder or something similar). 

Let me know what your thoughts are on this, I think something to this effect would remove all manual input required for adding new datasets, beyond defining the dataset and dictionary. 

P.S. @tposey28 I think you should be looped into all of these discussions ASAP as they pertain directly to the work you are doing in cleaning & organizing the upstream data. We can initiate a discussion on how best to coordinate these efforts

**Comment by maurolepore** [comment]
@jdhoffa, great to learn the impact of removing a GH account with open PRs. Thanks for educating me.

I like your idea of creating the `data_dictionary` on the fly. The only think that needs to be documented is the key-value pair `column`-`definition`. We could certainly do that via .csv files, which favors a spreadsheet-oriented workflow. Alternatively, we could use YAMAL files, which are perfect for key-value pairs and easier to type and read than the `tibble::tribble()` approach I proposed.

You are the main contributor so the approach should now fit your preferred workflow. Which is it? (How do you actually go about defining each column of a new dataset? Do you use a spreadsheet? If so, in Excel, Google Sheets, somewhere else? If not, how do you do it?).

Thanks for identifying the connection with Taylor. It's still unclear to me but I really look forward to learning what it is and working with him.

**Comment by jdhoffa** [comment]
@maurolepore several points in this comment:
re: mergine github accounts - FYI any open pull requests, issues, wikis, gh-pages and owned repos are deleted upon deletion of an account. the key step is simply to transfer ownership to the account to be kept. will keep you posted if i learn anything else new. I didn't find a suitable way to transfer commit history (honestly I didn't care enough to try that hard haha)

re: data_dictionary on the fly - I think it would be best to bias toward a spreadsheet-oriented workflow. i have been formatting the data both in a spreadsheet, and then in R (for generating more data examples etc.) but beyond myself, i think the .csv method would definitely be preferred.

**Comment by maurolepore** [comment]
@jdhoffa, do you have at hand the links you used to learn about the impact of deleting a GitHub account and about transferring ownership? I'd like to capitalize your effort by recording your new knowledge at https://github.com/2DegreesInvesting/resources

Great, I'll draft a spreadsheet-oriented solution for defining columns of new datasets.

**Comment by tposey28** [comment]
Absolutely, thanks for looping me in.

Essentially, a lot of files important to the Portcheck process, as well as the Gitbook / CMP work Pranav has been doing, are simply exports of tables from the database I manage. This is partially because no real system was put in place for pulling this data consistently. I proposed that a lot of these views ought to be created in R, not in SQL, allowing viability and flexibility. If this is the route you're already going in, I can provide the view definitions / queries, and be a source for column definitions.

**Comment by maurolepore** [comment]
Great. @jdhoffa are you happy to continue to manage/coordinate our joint efforts? This is the division of roles I imagine. What would you suggest?

1. @jdhoffa and @tposey28 coordinate what needs to be done, and `@mention` me to discuss how and where (which repo).
2. @jdhoffa and @tposey28 submit PRs or assigns issues to me.
3. We follow from there and repeat.

**Comment by jdhoffa** [comment]
I'm happy to continue to coordinate. 

I don't know that @tposey28 will necessarily be contributing that actively as his DataStore work is immense. My goal in looping him in is more to make sure he is aware of this repo/ what we are doing with it and make sure it's in line with whatever he has planned in the back end. 

I think in the long term these two things could work in tandem, so I just wanted to start that conversation asap. Anyway, let's discuss in more detail on Monday

**Comment by maurolepore** [comment]
@jdhoffa, okay,  thanks for clarifying. So I won't expect any specific action on that front right now.

**Comment by maurolepore** [comment]
@jdhoffa, 

`data_dictionary()` now works on the fly (02297cd). `<new_data>` must have a corresponding `<new_data>.csv` file in inst/extdata/. This location is compulsory -- files in inst/ are installed with the package, and `data_dicitionary()` pull them from the user's system (in case you are curious, via `system.file()`).

As we discussed on slack, we may help users to create data dictionaries for their contributed data via some kind of template, e.g.:

image

And we could document our expectations in `?data_dictionary()` and point to that in the [issue template for contributed datasets](https://github.com/2DegreesInvesting/.github/blob/master/.github/ISSUE_TEMPLATE/dataset.md).

What do you think?

**Comment by jdhoffa** [comment]
this seems like a suitable solution to me

**Comment by maurolepore** [comment]
@jdhoffa, 

From our chat on slack I feel we are now ready to remove the "draft" status of this PR, and squash-merge. I'll go ahead.

**Pull request merged**
