### PR TITLE
Bugfix: add appropriate whitespace to elements of name_reductions.csv (#9)

### PR DESCRIPTION
**Pull request by jdhoffa**
I have adjusted name_reductions.csv to include the relevant whitespace. 
No difference now between pacta::data.name.reductions$From and r2dii.dataraw::name_reductions$from

### CODE REVIEW

**Comment by maurolepore** [comment]
Thanks @jdhoffa!

Where do we use this dataset? I know we need it in `convert_customer_name()` ([PR](https://github.com/maurolepore/r2dii.match/pull/1 )). Will we use it somewhere else?

**Comment by jdhoffa** [comment]
Only there as far as I know

**Comment by maurolepore** [comment]
Thanks. I ask because I'm trying to think of names that read well when we put together all of these:

* the function, 
* argument, 
* argument value (this dataset)

Compare:

Except with a lot of context, I don't find this particularly clear

```
# Original
a_string %>%
  simplifyName(reductions = name_reductions)
```

I find this clearer, but likely you have more ideas for even clearer/more-accurate names?

```
# Work in progress
a_string %>%
  convert_customer_name(from_to = lookup_rules)
```

Or maybe 

```
# Work in progress
a_string %>%
  convert_customer_name(lookup = rules_from_to)
```

Or maybe 

```
# Work in progress
a_string %>%
  convert_customer_name(from_to = from_to_rules)
```

I do acknowledge, however, that the jargon "reduction" may be already too deeply embedded in 2dii, and "clarifying" things may actually confuse people. 

What do you think?

**Comment by jdhoffa** [comment]
'reduction' jargon is by no means embedded, happy to make it clearer. For the record, I'm partial to:
```
# Work in progress
a_string %>%
  convert_customer_name(from_to = lookup_rules)
```

**Comment by maurolepore** [comment]
Closed by https://github.com/2DegreesInvesting/r2dii.match/commit/0415b8ebca24a213a174e5fa3d1af56505d9cfca

**Pull request closed without merging**
