### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Add a deprecation notice in advance of archiving the repo.

If anyone knows of an alternative project to refer to, please add a reference. If you know of anyone who should review, but isn't on the list, please add them.

If there are no objections, this commit will be merged, and repo will be archived in 1 week.

### CODE REVIEW

**Comment by maurolepore** [comment]
The star of this package was [`take_snapshot()`](https://2degreesinvesting.github.io/r2dii.dataraw/reference/take_snapshot.html), which I think aspired to do data preparation. 

@cjyetman, do you recognize the names of the datasets in the examples section here?
https://2degreesinvesting.github.io/r2dii.dataraw/reference/possible_snapshots.html

Are those datasets now handled in the data-preparation project you maintain?

**Comment by cjyetman** [comment]
I do recognize those dataset names, but I don't know anything about this repo or what taking a snapshot means.

**Comment by maurolepore** [comment]
Yeah, this project never really saw the light so I don't think anyone will miss it.

Alex, if you still would like to leave a note pointing somewhere useful, it seems pretty safe to say something like: For anything related to preparing data for the PACTA methodology see instead https://github.com/2DegreesInvesting/data_preparation (private).

**Comment by AlexAxthelm** [comment]
@maurolepore @cjyetman updated with reference to current work.

**Review by maurolepore — APPROVED** [review]

**Pull request merged**
